services:
  api:
    build: .
    container_name: sales-rag-api
    ports:
      - "8000:8000"
    environment:
      - AWS_REGION=${AWS_REGION}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - S3_VECTOR_BUCKET_NAME=${S3_VECTOR_BUCKET_NAME}
      - S3_VECTOR_INDEX_NAME=${S3_VECTOR_INDEX_NAME}
      - VECTOR_DIMENSION=${VECTOR_DIMENSION}
      - BEDROCK_MODEL_ID=${BEDROCK_MODEL_ID}
      - BEDROCK_GENERATION_MODEL_ID=${BEDROCK_GENERATION_MODEL_ID}
    volumes:
      - ./data:/app/data
    command: uvicorn src.api.main:app --host 0.0.0.0 --port 8000 --reload

  streamlit:
    build: .
    container_name: sales-rag-ui
    ports:
      - "8501:8501"
    environment:
      - API_BASE_URL=http://api:8000
    depends_on:
      - api
    command: streamlit run streamlit_app.py --server.address 0.0.0.0 --server.port 8501